### ISSUE TITLE
Firewall Active Sessions not graphing

### ISSUE THREAD

**Issue by sbakara** [heringa/observium#1]
Hi Heringa,
Thank you so much for these plugins. I have failed to get the SRX (SRX 3600, SRX650) active sessions to graph. Only the Netscreen firewalls have the active session graphs up. 
![fw_graph](https://cloud.githubusercontent.com/assets/7382477/9516362/da1cc24e-4cb0-11e5-9be4-2cbde30235c5.PNG)

SB.

**Comment by heringa** [comment]
i'll have a look into this...

**Comment by heringa** [comment]
I reviewed all parts, but still don't know what causes this issue.
Are you running the latest version of Observium?
Did you apply all patches correctly?

Since last month Observium collects and presents this data itself. There is no direct need for this plugin anymore.
You could use:
your-observium-url/devices/type=firewall/format=graphs/sort=hostname/graph=jnxJsSPUMonitoringFlowSessions

Erwin.

**Comment by sbakara** [comment]
Here are the details of the version I am running ![observium](https://cloud.githubusercontent.com/assets/7382477/9603843/37d4cb3e-50bc-11e5-9393-02312a9ada45.PNG)
I also applied the patches as instructed.

**Comment by heringa** [comment]
It seems that you are running a 2 year old version of observium.
Please upgrade to the latest version. (Current CE 0.15.6.6430)

**Comment by MissSB** [comment]
Thank you, I'll do that. Regards,Sharone-------- Original Message --------Subject: Re: [observium] Firewall Active Sessions not graphing (#1)From: heringa To: heringa/observium CC: "Sharone B." It seems that you are running a 2 year old version of observium.
Please upgrade to the latest version. (Current CE 0.15.6.6430)
